version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file: ./server/.env
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

